version: '3.8'

services:
  mongodb-test:
    image: mongo:latest
    container_name: mongodb-test
    ports:
      - "27018:27017"  # Different port from development
    environment:
      - MONGO_INITDB_DATABASE=testdb
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: mongod --logpath=/dev/null  # Reduce log noise during tests

  mongo-express-test:
    image: mongo-express:latest
    container_name: mongo-express-test
    ports:
      - "8082:8081"  # Different port from development
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-test
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb-test
    networks:
      - test-network

  test-runner:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    container_name: testwigr-test-runner
    depends_on:
      - mongodb-test
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-test:27017/testdb
      - APP_JWT_SECRET=test_secret_key_for_jwt_tokens
      - APP_JWT_EXPIRATION=86400000
    volumes:
      - ../src:/app/src
      - ../build/reports:/app/build/reports
      - ../build/test-results:/app/build/test-results
      - gradle_cache:/root/.gradle
    networks:
      - test-network
    command: test

networks:
  test-network:
    driver: bridge

volumes:
  gradle_cache:
    driver: local
